version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Berlin
    assignees:
      - stnokott
    reviewers:
      - stnokott
    commit-message:
      prefix: github
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Berlin
    assignees:
      - stnokott
    reviewers:
      - stnokott
    commit-message:
      prefix: go
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      timezone: Europe/Berlin
    assignees:
      - stnokott
    reviewers:
      - stnokott
    commit-message:
      prefix: docker
