# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - go mod tidy
    - go mod verify
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    binary: app
    ldflags:
      - -s # -s and -w reduce binary size, but prevent debugging (not necessary for production build)
      - -w
      - -X github.com/stnokott/r6prom/constants.LOG_LEVEL=1 # set log level to INFO
changelog:
  sort: asc
  abbrev: -1
  use: github
  filters:
    exclude:
      - "^style"
      - "^test"
      - "^Merge branch"

  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
    - title: Documentation
      regexp: "^docs"
    - title: Code refactor
      regexp: "^refactor"
    - title: Performance Optimization
      regexp: "^perf"
    - title: Dependencies
      regexp: "^build(deps)"
    - title: Pipeline
      regexp: "^ci"
    - title: Others
      order: 999
release:
  target_commitish: "{{ .Commit }}"
  github:
    owner: stnokott
    name: r6prom
  name_template: "v{{ .Version }}"
  footer: |
    ### Installation
    `go get github.com/stnokott/{{ .ProjectName }}`
    `go get github.com/stnokott/{{ .ProjectName }}@v{{ .Version }}`

dockers:
  - image_templates:
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: "Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-armv7"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-armv7"
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: "Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm/v7"
  - image_templates:
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
    dockerfile: "Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-armv7"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/stnokott/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/stnokott/{{ .ProjectName }}:{{ .Version }}-arm64"
